### ISSUE TITLE
Value should be a JSON object.

### ISSUE THREAD

**Issue by adrensnyder** [szimszon/backuppc_monitor_zabbix#3]
Hi,

i'm trying your script but everytime get "Value should be a JSON object."
The script is in another folder because i have others script and visudo configured.

Server versione 3.0

I'm throught a proxy 3.0.2 and an agent 3.0.2
Basic script zabbix-backuppc.pl work correctly

system.run[sudo -u backuppc /etc/zabbix/externalscripts/zabbix-discover-backuppc.pl] [t|{  "data":[
    {"{#BACKUPHOST}":"pc1"}
,    {"{#BACKUPHOST}":"pc2"}
,    {"{#BACKUPHOST}":"pc3"}
,    {"{#BACKUPHOST}":"pc4"}
,    {"{#BACKUPHOST}":"pc5"}
,    {"{#BACKUPHOST}":"pc6"}
,    {"{#BACKUPHOST}":"pc7"}
  ]}]

I try to find log of it on server, proxy or client but nothing.

Any suggestion?
Thanks

**Comment by szimszon** [comment]
I doesn't upgraded to 3.0 yet.
Could you run the script
  sudo -u backuppc /etc/zabbix/externalscripts/zabbix-discover-backuppc.pl
with the zabbix user?

**Comment by adrensnyder** [comment]
Yes. The JSON i've paste you in previous message is the resultant of this command:
/usr/sbin/zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf -t system.run["sudo -u backuppc /etc/zabbix/externalscripts/zabbix-discover-backuppc.pl"]

Same if i launch only the pl: 
sudo -u backuppc /etc/zabbix/externalscripts/zabbix-discover-backuppc.pl
{  "data":[
    {"{#BACKUPHOST}":"pc01"}
,    {"{#BACKUPHOST}":"pc02"}
,    {"{#BACKUPHOST}":"pc03"}
,    {"{#BACKUPHOST}":"pc04"}
,    {"{#BACKUPHOST}":"pc05"}
,    {"{#BACKUPHOST}":"pc06"}
,    {"{#BACKUPHOST}":"pc07"}
  ]}

Also with zabbix user the same. The data get sended correctly but i think is something on the JSON that zabbix don't like. I also tried modifing the resultant JSON hardcoding but nothing.
I will make some tests and update you if i get it work.

Thanks thousand

**Comment by szimszon** [comment]
I'll be thankful for that!

**Comment by adrensnyder** [comment]
I found a problem with my sudoers file that was modified for another program and give my a tty problem cause of that in execution from zabbix agent. I reset it and no more problems.
Your script work in wonderful way with 3.0. I try today to use on all other backup hosts.
Thanks thousand for your work
